### ISSUE TITLE
Add DSL expressions (Pester, PSate, psake etc.) to tree view

### ISSUE THREAD

**Issue by MindGirl** [mgr32/PsISEProjectExplorer#19]
The currently implemented display of the script functions in the Project Explorer pane is great. However with some PowerShell modules script authors just defines script blocks to make use of them. 
Examples are the unit test modules Pester (https://github.com/pester/Pester), PSate (https://github.com/jonwagner/PSate) or the build automation tool psake (https://github.com/psake/psake).
As it would be tedious to maintain a list of the commands for these modules, could you think of a way to make it extensible by the user or simply showing any function / cmdlet in the tree view that uses a script block?

Best Regards.

MindGirl

**Comment by mgr32** [comment]
Added automatic recognition of DSL expressions - in the tree view they will show as additional nodes under Powershell files:
![dsl](https://cloud.githubusercontent.com/assets/6533636/12224642/d06de032-b7f6-11e5-8602-a5425ab1caa7.png)

The builtin mechanism should be able to recognize typical expressions like Pester's Describe/It or DSC resources usage (approximately lines that start with constant string and ends with scriptblock), but it can also be extended with custom dictionary - `DslCustomDictionary` entry in configuration file (by default contains PSake and PSCI elements). The automatic recognition can be disabled in case of issues - `DslAutoDiscovery` entry (in this case only `DslCustomDictionary` will be used).

**Comment by MindGirl** [comment]
Wow, wonderful. Had not much time to play with it yet, but so far it is working great.
Thank you very much for this wonderful add-on!
