### ISSUE TITLE
Installer should properly detect "Documents" path

### ISSUE THREAD

**Issue by trondhindenes** [mgr32/PsISEProjectExplorer#31]
The installer (per-user) assumes that Documents live in the user'
s profile. This is often not the case.

**Comment by mgr32** [comment]
Thank you and sorry for delay :) Replaced $env:USERPROFILE\Documents with [Environment]::GetFolderPath("mydocuments").
The original implementation actually came from msdn, so they apparently got it wrong:
https://msdn.microsoft.com/en-us/library/dd878350%28v=vs.85%29.aspx

**Comment by mgr32** [comment]
Released in 1.2.4.
