### ISSUE TITLE
Crash on load due to access denied on folder

### ISSUE THREAD

**Issue by dsolodow** [mgr32/PsISEProjectExplorer#34]
At one point I changed my workspace to a folder on a remote system. 
Now when I import the psiseprojectexplorer module, it crashes with an access denied to that remote folder. 

That seems like a defect, but the other question is where does it store that workspace so I can tell it to stop looking there? :)

**Comment by mgr32** [comment]
Thanks for creating this issue - it should remove such locations during startup, but apparently it sometimes fails. 
You need to delete or modify file ${env:USERPROFILE}\Documents\WindowsPowerShell\Modules\PsISEProjectExplorer\PsISEProjectExplorer.config, where ${env:USERPROFILE} is normally c:\Users\<Your Username>.

**Comment by dsolodow** [comment]
I'd looked at that file, and it only had my local workspace directory in
it. Deleting it didn't solve the issue either.
However, what I noticed was that when I closed my ISE tab it asked me if I
wanted to save the untitled.ps1 and it wanted to save it in the remote
workspace directory.
Once I saved the untitled.ps1 in my local directory, the
PsISEProjectExplorer.config
file had the remote workspace in it. Deleting the .config file then fixed
the issue.

So it looks like there is an MRU for the ISE that it's looking at as well.

**Comment by mgr32** [comment]
This seems strange. I'm having problems with recreating the issue - tried the following:
1) When setting workspace to a shared folder it says 'Cannot use root directory x. Please select another path' and continues to work normally (workspace list not updated). I will also look into it, but seems to be a different issue.
2) When setting workspace to a shared subfolder it is successfully added to the workspace list. After restarting ISE it still works.
3) After removing permissions to the subfolder and restarting ISE it is automatically removed from the list.

Are you able to recreate the issue and if so, could you provide exact steps?

**Comment by mgr32** [comment]
Did the issue occur again? If yes, could you get the latest version and attach the log file when it happens again?

**Comment by dsolodow** [comment]
I think the newest version (1.2.3) fixed it; I went through steps to
re-produce it and it didn't re-occur.

**Comment by mgr32** [comment]
Thank you, I didn't do anything to fix it though - so for now I'll close it, but feel free to reopen (and attach log file) when it reoccurs.
