### ISSUE TITLE
Add three-state indexing option - index contents of all files, index contents of local files only, index no files

### ISSUE THREAD

**Issue by mgr32** [mgr32/PsISEProjectExplorer#35]

**Comment by claudiospizzi** [comment]
I would suggest not just adding a 'stop indexing' button, but also adding an 'disable indexing' option. In my case, I have quite a lot of scripts inside my main workspace. When I start ISE, the Project Explorer is in the profile script, so it get's startet too. But then it uses one CPU core (100%) to do the indexing up to multiple minutes.

**Comment by mgr32** [comment]
Good idea - it needs to look through all the directory structure, but parsing file contents could be optional (especially considering [PSParser.Tokenize method](https://msdn.microsoft.com/en-us/library/system.management.automation.psparser.tokenize%28v=vs.85%29.aspx) can be really slow for some DSC files and probably for other PS4/PS5 constructs too).

**Comment by mgr32** [comment]
Released in 1.4.1.
