### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by iainbrighton** [mgr32/PsISEProjectExplorer#36]
Probably a bit of a curve ball, but I'm having issues running PsISEProjectExplorer in combination with ISE Steroids (http://www.powertheshell.com/isesteroids/).

![image](https://cloud.githubusercontent.com/assets/7023258/6639992/480d533e-c98c-11e4-863b-55a744c888a5.png)

ISE Steroids has some functionality for monitoring external file changes and this has been disabled.

This exception occurred when collapsing a code block - I wouldn't have thought that PsISEProjectExplorer would be doing anything with margins and line numbers (not that I would know)? I didn't see any ISE Steroids error as the ISE crashed..

**Comment by mgr32** [comment]
Thank you, I don't think PsIseProjectExplorer updates any line numbers or margins (only moves cursor to given line number). I'm not sure whether this really comes from PsIseProjectExplorer or somewhere else, as it's possible it currently catches all exceptions coming from main ISE window... Will investigate.

**Comment by iainbrighton** [comment]
Hi Marcin,

I appreciate that this is a difficult one but I certainly get more frequent crashes with both PsISEProjectExplorer and ISESteroids loaded. Either on their own are pretty stable.

Is there any additional information I can capture when this happens?

Thanks, Iain

**Comment by mgr32** [comment]
Hi Iain,

I've confirmed that PsISEProjectExplorer actually (erroneously) catches all unhandled exceptions, even from different modules (I created a separate module that throws an exception from a new thread that it spawns, and PsISEProjectExplorer caught the exception from the new module and said it occurred in PsISEProjectExplorer). I'll fix it and add some more logging, and then try to recreate your issue with ISESteroids (I can see they seem to give a trial version for free). If I fail, I'll ask you to try to do it with the new version with improved logging.

Cheers,
Marcin

**Comment by iainbrighton** [comment]
Thanks Marcin. If I can try anything then please let me know. I got this one when saving a file with CTRL+S last night but whether it's the same issue I don't know..

![image](https://cloud.githubusercontent.com/assets/7023258/6651458/bfba94ec-ca3a-11e4-9526-6cb2aa9ddda1.png)

**Comment by mgr32** [comment]
I was not able to recreate the issue with ISESteroids, however I've added logging configuration (#38) and made ISE not close on unhandled exceptions (#37), so that you should be able to continue working after most exceptions (or at least save your work). I also updated the error text in order to try to give information about the exception source.
Could you download new release (v.1.2.3), set minLevel="Debug" (instead of "Error") in NLog.config file and try to recreate the issue? If successful, please attach the resulting log file.
Or if you're able to recreate it in a deterministic way, please send me the file which makes it break and steps how to reproduce.

The second exception (TreeViewModel) is clearly PsIseProjectExplorer issue (I also got it and described in issue #33) and most probably it's not related to the first one. I'll investigate this one soon (hopefully).

**Comment by iainbrighton** [comment]
OK - I've downloaded the latest build and set the logging level to debug. We'll see what happens! Thanks for all your help ;)

**Comment by mgr32** [comment]
Hi Iain, any update? Hopefully it doesn't crash any more ;)

**Comment by iainbrighton** [comment]
Hi Marcin,

I haven't had a chance this week as I've been delivering training. I do have some development time scheduled for next week so will know more then!

Thanks, Iain

On 20 Mar 2015, at 20:00, Marcin Grzywa <notifications@github.com> wrote:

Hi Iain, any update? Hopefully it doesn't crash any more ;)

**Comment by mgr32** [comment]
Hi Iain, thanks for update. I also haven't lately had much time for this project as I've been focused on https://github.com/ObjectivityBSS/PSCI :)

**Comment by iainbrighton** [comment]
OK - been in the ISE all day and had quite a few exceptions thrown (although no longer kicked out of the ISE!). The report is available here: https://gist.github.com/iainbrighton/126d0afa425948baecb2 - some of them look like ISE Steroids and some PsISEProjectExplorer.

**Comment by mgr32** [comment]
Thank you Iain, some of them are clearly from Steroids, some from ProjectExplorer (will add these as issues) and some from who-knows-where. Since you can keep working after they occur, I think I'll just remove the popup and only log the errors to the log file.

**Comment by mgr32** [comment]
In 1.2.4 message boxes should not appear. Please reopen if they do.
