### ISSUE TITLE
Stop searching for workspace when PSD1/PSM1 found

### ISSUE THREAD

**Issue by wekempf** [mgr32/PsISEProjectExplorer#47]
I have PS1 files higher up in the directory structure, so it this extension chooses the wrong directory (by default) when determining the workspace root. Modules are, generally, analogous to projects so it seems best to assume a module directory (a directory with a PSD1 or PSM1 file) is a workspace root.

**Comment by mgr32** [comment]
Thanks, released in 1.2.4.

**Comment by wekempf** [comment]
Nice! Very quick turn around on that issue report. Thanks.
