### ISSUE TITLE
Extend config file posibilities

### ISSUE THREAD

**Issue by claudiospizzi** [mgr32/PsISEProjectExplorer#53]
I have a special use case for the PsISEProjectExplorer module:
In my environment, I synchronize the WindowsPowerShell folder with Dropbox over all my computers, by using a symlink from the documents folder into the Dropbox folder. The PsISEProjectExplorer module is stored in this directory too. My problem now, the config file PsISEProjectExplorer.config is synchronized - but the paths for the Workspace directories are different on each computers.

Would be great if we can extend the config file posibilities:
- Option 1: Use a second location for the config file (e.g. the user profile folder %appdata%). We then have to define, which file hast the priority.
- Option 2: Use an environment variable prior to the module import, to configure the config file path
(e.g. $Env:PsISEProjectExplorer_ConfigFile = 'C:\Path\To\config'). If it is set, this path will be used. Else the default config flle path is used.

I will provide a pull request, but first I like to ask, maybe some has a better idea?

What do you think about that?

**Comment by mgr32** [comment]
Do you see any benefits in having the configuration file it in two places? If not, I think we could just move it to %localappdata%\PsISEProjectExplorer (as %appdata% points to Roaming folder).

We would probably need to provide a migration mechanism, so that users would not lose their configuration when upgrading to new version. But that should be simple - in `Install_to_UserModules.ps1` we can move the file from \<mydocuments\> to %localappdata% if it's not already there.

**Comment by claudiospizzi** [comment]
No, I see no benefits for having two configuration files. I just don't wanted to touch your config file concept, so I proposed an extension. But if you are open to move the config file to another location, it would be better to stick with one config file. As you proposed, we should place it into %localappdata%\PsISEProjectExplorer.

Will the Install_to_UserModules.ps1 script automatically be executed when a module is updates by the user - I think not? Maybe we can consider to move the config file at the beginning of the PsISEProjectExplorer.psm1 file, so the config file will be moved when the modules is loaded.

For the future, we gain the benefit, that the config file is stored separate to the module and will not be overwritten, if the module gets and updates.

**Comment by mgr32** [comment]
You're right, PsISEProjectExplorer.psm1 is better than Install_to_UserModules.ps1. If you provide a pull request, I'll merge it and release a new version.

**Comment by iainbrighton** [comment]
Moving the configuration file outside of the module directory will be welcomed. I currently sync my Powershell modules via OneDrive (and added the path the PSModulePath environment variable on each machine). I leave the PsISEProjectExplorer module in each machine's 'Documents\WindowsPowerShell\Modules" folder as that's not synchronised, but now have to maintain multiple installations!

**Comment by claudiospizzi** [comment]
I've created the pull request #54 

@iainbrighton Nice you've joined this discussion, because since I've saw you using PsISEProjectExplorer in the "Man vs Test Lab" session at PowerShell Summit in Stockholm, I use it too. :-)

**Comment by mgr32** [comment]
Thanks a lot, I will test it and should be able to release new version this week.

It's nice to hear PsISEProjectExplorer is still useful (especially considering how powerful [Powershell Tools for Visual Studio 2015](https://visualstudiogallery.msdn.microsoft.com/c9eb3ba8-0c59-4944-9a62-6eee37294597) is) and even shown at conferences :)
