### ISSUE TITLE
Errors parsing XML files

### ISSUE THREAD

**Issue by iainbrighton** [mgr32/PsISEProjectExplorer#56]
When having .ps1xml/.xml files in a project/workspace, PsISEProjectExplorer v1.2.5 now seems to parse these incorrectly (or at least flag unnecessary errors). Here's an example with the Pester module loaded:

![image](https://cloud.githubusercontent.com/assets/7023258/10426960/2e40715e-70dd-11e5-8c15-e0543dc89e1b.png)

Can an option be added to not parse .ps1xml/.xml files?

**Comment by mgr32** [comment]
Sure, will be fixed in next version.

**Comment by mgr32** [comment]
Fixed and released in 1.2.6.
