### ISSUE TITLE
ISE crash

### ISSUE THREAD

**Issue by jvedie** [mgr32/PsISEProjectExplorer#59]
I'm having ISE crash randomly when using PsISEProjectExplorer. It seems to be after a some heavy use and days of usage. I don't have other specifics to help you. You'll find the error message attached
![capture1](https://cloud.githubusercontent.com/assets/13870189/10606085/999953f4-7730-11e5-9f28-feb6848fb358.PNG)

**Comment by mgr32** [comment]
Thanks @jvedie. It looks like you're using an older version - please ensure you're using 1.2.6 (error handling has been improved in 1.2.3).

**Comment by jvedie** [comment]
Thanks, I've installed the latest version and I'll keep monitoring ISE crash on my system. By the way, the PSD1 file and Get-Module cmdlet still returns version 1.0. Normal ?

**Comment by mgr32** [comment]
Right, I've never updated psd1 file - will do in next version :)

**Comment by jvedie** [comment]
My ISE just crashed with the bug we've been talking about last week. I'm running the latest version and it seems that the problem isn't fixed. Any idea?

**Comment by mgr32** [comment]
I believe it shouldn't be possible it crashed with the same exact message as the text 'Please create an issue at ...' is no longer in the codebase. To confirm you have the latest version - do you have 7 icons on the toolbar (the first one should be 'Search using regex') in your PsISEProjectExplorer?

**Comment by jvedie** [comment]
I just have 6 icons. I've attached a capture showing what I have.
![capture1](https://cloud.githubusercontent.com/assets/13870189/10762352/0be6b0ec-7cc6-11e5-9ab3-b924bb8b10d1.PNG)

I just redownloaded the latest version (1.2.6) from Github repo in the release tab. I've replaced all the 6 files in my module directory and reloaded the ISE. Nothing change I still have 6 icons.

**Comment by mgr32** [comment]
This is definitely the old version - please check if old version of PsISEProjectExplorer has not been added to some other directory on your $env:PSModulePath than the one you're copying to.

**Comment by mgr32** [comment]
Oh and look what is in your profile file (%mydocuments%\WindowsPowerShell\Microsoft.PowerShellISE_profile.ps1) - I suspect there must be reference to a directory with old version somewhere.

**Comment by jvedie** [comment]
Indeed I just discovered that I had an older version located in my user Module folder under C:\Users\<User>\Documents\WindowsPowerShell\Modules which took precedence over the one located in the system modules folder. I didn't know about this mecanism. Thanks for the tip :-)
I'll now be able to try the new features you implemented in the latest version. Thanks for you work.

**Comment by mgr32** [comment]
Do you still encounter the crashes? If not, I'm going to close the issue :)

**Comment by jvedie** [comment]
Hi Marcin,
No, everything is fine now, no more crashes, you can close the issue.
Thanks
Julien

2015-12-16 8:45 GMT+01:00 Marcin Grzywa <notifications@github.com>:

**Comment by mgr32** [comment]
Thanks for update.
