### ISSUE TITLE
Create Folder Bug

### ISSUE THREAD

**Issue by claudiospizzi** [mgr32/PsISEProjectExplorer#60]
When I try to create a folder inside an existing folder, it will wrongly rename the parent folder instead of create a new child folder:

Steps to reproduce the bug in PSISEProjectExplorer:
1. Go into a folder, e.g. \_Test\FolderA
2. Right click on FolderA, select "Add", select "Directory"
3. Type the following as a name, for the '-' please use the numblock key: 2015-10-22_Test 
4. As soon as you have hit the numblock key '-', it will rename the parent folder to what you have typed, in my case to '2015'

I can reproduce it on two devices (Windows 7, Windows 10) with PowerShell 5 and PSISEProjectExplorer version 1.0 (11.10.2015).

**Comment by mgr32** [comment]
Thanks @claudiospizzi - will fix in next release.
