### ISSUE TITLE
Add support for configurable number of workspaces to remember

### ISSUE THREAD

**Issue by poshcodebear** [mgr32/PsISEProjectExplorer#61]
Currently, this number is controlled in UI\ViewModel\WorkspaceDirectoryModel.cs on line 56, and is hard coded to 5 directories.  It would be useful to be able to configure this easily.

**Comment by mgr32** [comment]
Actually, it's not hardcoded but read from config file, located at %LOCALAPPDATA%\PsISEProjectExplorer\PsISEProjectExplorer.config.

You just need to add following line:
<add key="MaxNumOfWorkspaceDirectories" value="10" />

In 1.2.7/1.3.0 node "MaxNumOfWorkspaceDirectories" will always be present in the config file (with default value 5), just to improve discoverability.
