### ISSUE TITLE
Support for PowerShell 5.0 Classes and Methods

### ISSUE THREAD

**Issue by Golosok** [mgr32/PsISEProjectExplorer#62]
Classes and Methods are introduced in Powershell 5.0 
Can you add support for Classes and Methods in project browser?
Thanks,
Alex

**Comment by mgr32** [comment]
Hi @Golosok, does the support for classes look good in 1.3.0?

**Comment by Golosok** [comment]
Yes, works excellent. 
I can see both Members and Methods.
Thank you very much!

**Comment by mgr32** [comment]
That's good to hear, thanks for opening the issue and for feedback :)
