### ISSUE TITLE
Move status message to the ISE status bar

### ISSUE THREAD

**Issue by claudiospizzi** [mgr32/PsISEProjectExplorer#68]
Because we're getting more and more icons on top of the Project Explorer Add-In, I would suggest to move the status message to the ISE status bar.

**Comment by mgr32** [comment]
If you mean the global ISE status bar, I'm not sure if it's possible without hacking - I think plugins can do what they like inside their own tab, but not outside it. I can see on the [ISE Object Model Hierarchy](https://technet.microsoft.com/en-us/library/dd819500.aspx) there is `StatusText` property, but it is read-only.

**Comment by mgr32** [comment]
Descoped.
