### ISSUE TITLE
Error during installation from Gallery

### ISSUE THREAD

**Issue by artisticcheese** [mgr32/PsISEProjectExplorer#70]
Getting error during Install-Package. Running ISE as admin.

PackageManagement\Install-Package : The member 'FileList' in the module manifest is not valid: Cannot find drive. A drive with the name 'O' does not exist.. Verify that a valid value is specified for this field in the 
'C:\Users\admin\AppData\Local\Temp\1673533330\PsISEProjectExplorer\PsISEProjectExplorer.psd1' file.

**Comment by mgr32** [comment]
Thanks, will fix in a minute :)

**Comment by mgr32** [comment]
Should be fine now, please let me know if it works for you.

**Comment by artisticcheese** [comment]
Cool and fast. Works fine now
