### ISSUE TITLE
Feature request:Add ability to deploy file to production share

### ISSUE THREAD

**Issue by artisticcheese** [mgr32/PsISEProjectExplorer#71]
Please add ability to define production destination for a file so it can be copied over after local editing/debugging is done.

**Comment by mgr32** [comment]
Do you mean something like a keyboard shortcut that would allow to copy currently opened file to a specified UNC path (that user would enter in a message box for the first time)?

**Comment by artisticcheese** [comment]
yes or button. I'm not sure what people usually do in such cases since I have to do it pretty frequently. I develop module locally and then deploy to central location when I'm done where clients can load it on demand. This location is on UNC and right now and for different modules/scripts it's different. A lot of other editors has this functionality. They usually create file the same name as current file and some obscure extension like (.deploy) which hold information where production copy shall go to.

**Comment by mgr32** [comment]
OK, I usually have a continuous integration server that does it for me after pushing to Git, but it sounds ok for ad-hoc work. If you give me name of an editor that has it implemented well, I'll look into it when time allows.

**Comment by artisticcheese** [comment]
Powershell studio has it and add on for PowerGUI here (http://en.community.dell.com/techcenter/powergui/m/script-add-ons/20438959) has this functionality
