### ISSUE TITLE
File stays 'selected' so when selecting a new file it want to move it, very annoying

### ISSUE THREAD

**Issue by dotps1** [mgr32/PsISEProjectExplorer#74]
I have been using this for a week or so and it has been amazing, and then all the sudden, after selecting a file, it appears to stay selected, so when I want to select a different file, it asks me to confirm my action to move the file.  Very annoying, and I cannot seem to figure out how to make this stop, or why it started happening, because it did not do this for the first week of use.
![capture](https://cloud.githubusercontent.com/assets/1016996/14817503/b75773be-0b85-11e6-81fe-3801231e2747.gif)
I really hope this is a simple fix, because its very frustrating.  Thanks.

*edit*
a reinstall did not seem do anything.

**Comment by mgr32** [comment]
Thanks, this is strange and I've never encountered it. Few questions:
* Are you using PsISEProjectExplorer version 1.3.0?
* What is your version of Powershell and Windows?
* Does this happen at any workspace directory? 
* Are you using mouse as your input device or touchpad / touchscreen / something else? 
* Could you try deleting directory `%LOCALAPPDATA%\PsISEProjectExplorer`?

**Comment by dotps1** [comment]
I know right, its very annoying, right clicking on an item helps somewhat as a workaround.

yes, using version 1.3.2
WMF 5, WIndows 10 Pro x64
Yes, every workspace.
I do have a touchscreen (M$ Surface Pro 4) but it is docked and I am using a mouse and keyboard.
tried this, did not help unfortunately.

**Comment by dotps1** [comment]
OMG, actually, if I move the ISE to my actual surface screen, rather then an external display, seems fine.  So, I'm really not sure what to say about that.

**Comment by mgr32** [comment]
Interesting, now at least I can google for such issues if I'm not able to reproduce it myself :) I'll take a look with high priority when time allows.

**Comment by dotps1** [comment]
sounds great, and thanks!

**Comment by mgr32** [comment]
I suspect this might be fixed in 1.4.0 (unreleased yet) after fixing #15. Could you try [PsISEProjectExplorer-1.4.0-preview.zip](https://github.com/mgr32/PsISEProjectExplorer/blob/master/PsISEProjectExplorer-1.4.0-preview.zip) and let me know if it's any better?
If you installed 1.3.2 by PSGallery you would probably need to uninstall it first and then install the new version from zip (directions are on the main github site).

**Comment by dotps1** [comment]
Sorry, I cannot test this until tomorrow, I am working from home today, and I don't have a dock here.  That seemed to be when the issue occurred, but I will let you know first thing tomorrow.  Thanks!

**Comment by mgr32** [comment]
No hurry, thanks for update :)

**Comment by dotps1** [comment]
it seems to be fine with the new layout and larger icons.  Thanks!
