### ISSUE TITLE
Anyone else noticed File list changing with windows 10 updates

### ISSUE THREAD

**Issue by imorrish** [mgr32/PsISEProjectExplorer#79]
I used to be able to set my Workspace to be a OneDrive location but it is now not showing any files in this location.

**Comment by imorrish** [comment]
Same problem in VS Code. Good description of issue and resolution here
https://github.com/Microsoft/vscode/issues/27285

**Comment by mgr32** [comment]
Is this related to 'Files On Demand' functionality, as described in #80?

**Comment by mgr32** [comment]
Duplicate of #80 (fix ready).
