### ISSUE TITLE
How to remove a workspace?

### ISSUE THREAD

**Issue by vfuyong** [mgr32/PsISEProjectExplorer#83]
May I know how to remove an existing workspace? Thanks.

**Comment by mgr32** [comment]
You would need to manually edit PsISEProjectExplorer.config (located at `%LOCALAPPDATA%\PsISEProjectExplorer`) - key named `WorkspaceDirectories`.

**Comment by vfuyong** [comment]
@mgr32 Thanks, that is helpful.
